### ISSUE TITLE
inclination tag missing?

### ISSUE THREAD

**Issue by cagnulein** [h4l/zwift-workout-file-reference#3]
in what's on zwift site i saw that some runners workout have the inclination field.

**Comment by bertrandpasquier** [comment]
Hi Roberto, 

This feature has been added with latest Zwift Academy. 
Striclty speaking, it is not an "inclination field"
It simply relies on UI text replacement using new hidden xml attributes ...

Example (matching with screenshot) : 
`<SteadyState Duration="60" Power="0.5" pace="1" replacement_prescription="WALK" replacement_verb="No Incline" hide_set_speed="1" NeverFails="1" >`

Notes : 
- you can hide speed with `hide_set_speed="1"` (hue, self explicit ...)
- you can specify that star is always granted for step with `NeverFails="1"` (helpful for rest steps)

Best regards (and thanks for your impressive work)

Bertrand PASQUIER
thePainCave.net
<img width="507" alt="screenshot  2021-12-20 à 15 53 09" src="https://user-images.githubusercontent.com/97675812/152985167-9b57b0ed-7558-408b-ae12-bc9e92b741b3.png">

**Comment by cagnulein** [comment]
hah great, thanks @bertrandpasquier 
I was saying so because in my current project https://github.com/cagnulein/qdomyos-zwift/issues/589 i'm using these files and it will be great if also the incline will be managed (giving auto speed and auto inclination to all the treadmills!)
Thanks for the clarification.
Have a nice day

**Comment by bertrandpasquier** [comment]
I am one of your proud users (I'm owning a Domyos Intense Run Treadmill).
So, I'd guessed the purpose of your question !

Have a nice day too ...

PS :  I want to write an article about your app on my Zwift blog (which is one the largest one for french-speaking people). Feel free to contact me if you have information.

**Comment by cagnulein** [comment]
Wow great! Did you use the training program? We thought about adding the https://whatsonzwift.com/ integration, but the owner said me that there was a legal issue about zwift and the zwo usage.

Do you have any contact with Zwift?

Great about the article! If you want, feel free to send me an email to roberto.viola83 at gmail.com

**Comment by bertrandpasquier** [comment]
Great idea, but copyright infringement, especially for built-in workouts that are not downloadable on WoZ ...

Yep, I have some contact with Zwift team. 
But as the French proverb says: if you don't need anything, feel free to ask them... 😅
